### ISSUE TITLE
you should correct the path

### ISSUE THREAD

**Issue by grandmaster8** [MoonlightOwl/illuminator#1]
https://github.com/MoonlightOwl/illuminator/blob/384f65a9e6bf3faaaa8c4075619d7917b92b795b/spec/spec_helper.cr#L2

require "src/illuminator"
Сделай красиво. Настрой проект что бы он работал нормально.

**Comment by MoonlightOwl** [comment]
Nope, I should not.
This is a pretty much correct way to require files from the specs.
